### ISSUE TITLE
docs: contributing guidelines

### ISSUE THREAD

**Issue by elijaholmos** [Leyline-gg/pog-api#56]
as the API nears a functional release, it would prudent to allocate some resources to the preparation of a `CONTRIBUTING.md ` file & related contributing guidelines & criteria, in the name of transparency and open-source development. 

placeholder issue to be groomed further.

**Comment by nico-leyline** [comment]
Thanks @elijaholmos, make sense, I think we might need more than just the contributing guidelines but maybe separated tickets? Here they provide a full overview https://opensource.guide/starting-a-project/ so in addition i think we need to: 
- choose a licence
- write a ReadMe doc
- write contributions guidelines
- establish a code of conduct
- ...
